// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { BackupRestore } from '../../autocrud/lib/components/BackupRestore';

export const Route = createFileRoute('/autocrud-admin/backup')({
  component: BackupPage,
});

function BackupPage() {
  return <BackupRestore resourceNames={['investigation', 'rca-investigation', 'conversation', 'collection', 'source-doc', 'doc-chunk', 'wiki-page', 'wiki-build-state', 'kb-chat', 'notification', 'citation-event', 'check-run', 'sanity-result', 'telemetry-event']} />;
}
