// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { MigrationStatus } from '../../autocrud/lib/components/MigrationStatus';

export const Route = createFileRoute('/autocrud-admin/migrate')({
  component: MigratePage,
});

function MigratePage() {
  return <MigrationStatus resourceNames={['investigation', 'rca-investigation', 'conversation', 'collection', 'source-doc', 'doc-chunk', 'wiki-page', 'wiki-build-state', 'kb-chat', 'notification', 'citation-event', 'check-run', 'sanity-result', 'telemetry-event']} />;
}
