"""CardGenRunStore — CAS join state for the card-gen fan-out (#414).

A card-generation run over N documents is fanned out into N small
``CardGenJob(kind="process")`` jobs (one per doc) so they parallelise across
worker pods. Those jobs run independently — possibly on different pods, possibly
in parallel — so "every doc is digested" is a fact no single job owns. This store
is the agreement point, and it is deliberately **queue-agnostic**: correctness
rests on compare-and-swap against the resource's etag, NOT on the queue's
``partition_key`` serialization (which the RabbitMQ backend silently ignores).

The finalize trigger is NOT "whoever recorded the last doc" — that races (two
finishers can both see the set fill) and loses on crash (the last recorder can
die before triggering). Instead every finisher re-evaluates the gate
``done ∪ failed == total`` and races to flip the ``finalized`` flag under CAS;
exactly one wins and triggers finalize, and a crash before finalize just leaves
the gate open for the next finisher to win.

Mirrors :class:`workspace_app.kb.index_run.IndexRunStore`; the difference is that
this run also carries the FE-facing ``status`` (the split job returns before any
proposal exists, so the run — not the split job — is what the FE polls), and its id
is generated by ``start`` (a run spans a doc *set*, so there is no natural single
key like the index run's doc id). #511 P2: the review lifecycle (proposals +
decide / commit / dismiss) moved to :class:`~workspace_app.kb.card_proposal.CardProposalStore`
— this store is now purely the generation-run join; ``status`` is only the
generation lifecycle (``pending``/``running``/``done``/``error``).
"""

from __future__ import annotations

import logging
from collections.abc import Callable

import msgspec
from specstar import QB, SpecStar
from specstar.types import PreconditionFailedError, ResourceIDNotFoundError, RevisionStatus

from .card_gen import CardGenRun

_LOGGER = logging.getLogger(__name__)

# Per-run contention is bounded by the doc count; this is a generous backstop
# against a live-lock, not a tuning knob.
_MAX_CAS_RETRIES = 1000


class CardGenRunStore:
    """Read/CAS-write the per-run :class:`CardGenRun` join + FE-facing state."""

    def __init__(self, spec: SpecStar) -> None:
        self._rm = spec.get_resource_manager(CardGenRun)

    # ── seed / read ──────────────────────────────────────────────────
    def start(self, collection_id: str, doc_ids: list[str]) -> str:
        """Seed a fresh run over ``doc_ids`` (ordered, so finalize merges the
        staged digests deterministically) and return its id — what ``enqueue``
        hands back and the FE polls. Written as a draft revision so the split /
        process / finalize jobs can ``modify`` it in place under CAS (modify
        requires a draft). The run starts ``pending`` (PENDING to the FE) until
        the split job picks it up."""
        run = CardGenRun(collection_id=collection_id, doc_ids=list(doc_ids), total=len(doc_ids))
        return self._rm.create(run, status=RevisionStatus.draft).resource_id

    def get(self, run_id: str) -> CardGenRun | None:
        try:
            data = self._rm.get(run_id).data
        except ResourceIDNotFoundError:
            return None
        assert isinstance(data, CardGenRun)  # narrow Struct | Unset for ty
        return data

    def latest_finalized(self, collection_id: str) -> CardGenRun | None:
        """The collection's most-recently-finalized run (``done`` / ``error``),
        newest first — the source of the 待審核 tab's 'last run: drafted X → kept Y'
        summary. Both predicates are indexed (``collection_id`` + ``status``), so it
        never scans. Crucially it INCLUDES a run that kept 0 proposals — which the
        active-proposal queue can't show, yet is exactly the case a user needs
        explained. ``None`` if the collection has never finalized a run."""
        query = ((QB["collection_id"] == collection_id) & QB["status"].in_(["done", "error"])).sort(
            QB.created_time().desc(), QB.resource_id().asc()
        )
        for r in self._rm.list_resources(query.limit(1).build()):
            data = r.data
            assert isinstance(data, CardGenRun)  # rm is CardGenRun-typed; narrows ty
            return data
        return None

    # ── CAS mutations ────────────────────────────────────────────────
    def begin(self, run_id: str) -> None:
        """Flip ``pending`` → ``running`` when the split job picks the run up
        (PROCESSING to the FE while its process jobs run). Idempotent — a
        redelivered split leaves an already-running run untouched."""
        self._cas(run_id, lambda run: _to_running(run))

    def mark_done(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` was digested OK. Re-running
        the same process job (at-least-once redelivery) is a no-op."""
        self._cas(run_id, lambda run: _with_index(run, "done", doc_index))

    def mark_failed(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` gave up. Counts toward the
        finalize gate so a failed doc can't wedge the run in ``running`` forever."""
        self._cas(run_id, lambda run: _with_index(run, "failed", doc_index))

    def mark_skipped_indexing(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` was skipped because it was
        still indexing (no extracted text yet). It counts as ``done`` — the slot is
        closed so the finalize gate fits — AND is tracked in ``skipped_indexing`` so
        the funnel can attribute a low n_units to "not ready yet" rather than a
        drafter failure (P3, #506/#577 follow-up)."""
        self._cas(run_id, lambda run: _with_skipped_indexing(run, doc_index))

    def claim_finalize(self, run_id: str) -> bool:
        """Try to win the exactly-once finalize gate. Returns ``True`` for the
        single winner — only when every doc is accounted for
        (``done ∪ failed == total``) and the flag is not already claimed. All
        other finishers get ``False``. Crash-safe: if the winner dies before
        finalizing, the flag stays set but the finalize work is re-driven by
        redelivery; if it dies before even claiming, the gate is still open."""
        claimed = False

        def mutate(run: CardGenRun) -> CardGenRun | None:
            nonlocal claimed
            if run.finalized:
                return None  # already claimed by someone else
            if len(set(run.done) | set(run.failed)) < run.total:
                return None  # not every doc is accounted for yet
            claimed = True
            return msgspec.structs.replace(run, finalized=True)

        self._cas(run_id, mutate)
        return claimed

    def finish(
        self,
        run_id: str,
        *,
        status: str,
        n_units: int = 0,
        n_raw_drafts: int = 0,
        n_proposals: int = 0,
    ) -> None:
        """Stamp the terminal status (``done`` / ``error``) once finalize has run
        — this is what flips the FE from PROCESSING to COMPLETED / FAILED — and,
        in the same write, the finalize funnel counts (#506/#577 follow-up) so the
        FE can show 'drafted X → kept Y' without reading a log."""
        self._cas(
            run_id,
            lambda run: msgspec.structs.replace(
                run,
                status=status,
                n_units=n_units,
                n_raw_drafts=n_raw_drafts,
                n_proposals=n_proposals,
            ),
        )

    # ── machinery ────────────────────────────────────────────────────
    def _cas(
        self, run_id: str, mutate: Callable[[CardGenRun], CardGenRun | None]
    ) -> CardGenRun | None:
        """Optimistic read-modify-write. ``mutate(run)`` returns the next run, or
        ``None`` to abort with no write (an idempotent no-op). Retries on a
        concurrent writer until it wins or the run vanishes."""
        for _ in range(_MAX_CAS_RETRIES):
            try:
                res = self._rm.get(run_id)
            except ResourceIDNotFoundError:
                return None  # run cascaded away (collection deleted mid-flight)
            run = res.data
            assert isinstance(run, CardGenRun)
            new = mutate(run)
            if new is None:
                return None
            try:
                self._rm.modify(
                    run_id,
                    new,
                    status=RevisionStatus.draft,
                    expected_etag=res.info.etag,  # ty: ignore[unknown-argument]
                )
                return new
            except PreconditionFailedError:
                continue  # another writer won the race — re-read and retry
        raise RuntimeError(f"CardGenRun CAS exhausted retries for {run_id}")  # pragma: no cover


def _to_running(run: CardGenRun) -> CardGenRun | None:
    """Flip a pending run to running; a no-op (skip the CAS write) once it has
    already begun, so a redelivered split job can't reset progress."""
    if run.status != "pending":
        return None
    return msgspec.structs.replace(run, status="running")


def _with_index(run: CardGenRun, field_name: str, doc_index: int) -> CardGenRun | None:
    """Append ``doc_index`` to ``run.{field_name}`` unless already present
    (idempotent). Returns ``None`` to signal "no change" so the CAS write is
    skipped entirely."""
    current: list[int] = getattr(run, field_name)
    if doc_index in current:
        return None
    return msgspec.structs.replace(run, **{field_name: [*current, doc_index]})


def _with_skipped_indexing(run: CardGenRun, doc_index: int) -> CardGenRun | None:
    """Record a still-indexing skip: append ``doc_index`` to BOTH ``done`` (so the
    finalize gate closes) and ``skipped_indexing`` (so the funnel can attribute it).
    Idempotent — a no-op once already recorded, matching ``mark_done``."""
    if doc_index in run.skipped_indexing:
        return None
    return msgspec.structs.replace(
        run,
        done=run.done if doc_index in run.done else [*run.done, doc_index],
        skipped_indexing=[*run.skipped_indexing, doc_index],
    )
