"""CardGenRunStore — CAS join state for the card-gen fan-out (#414).

A card-generation run over N documents is fanned out into N small
``CardGenJob(kind="process")`` jobs (one per doc) so they parallelise across
worker pods. Those jobs run independently — possibly on different pods, possibly
in parallel — so "every doc is digested" is a fact no single job owns. This store
is the agreement point, and it is deliberately **queue-agnostic**: correctness
rests on compare-and-swap against the resource's etag, NOT on the queue's
``partition_key`` serialization (which the RabbitMQ backend silently ignores).

The finalize trigger is NOT "whoever recorded the last doc" — that races (two
finishers can both see the set fill) and loses on crash (the last recorder can
die before triggering). Instead every finisher re-evaluates the gate
``done ∪ failed == total`` and races to flip the ``finalized`` flag under CAS;
exactly one wins and triggers finalize, and a crash before finalize just leaves
the gate open for the next finisher to win.

Mirrors :class:`workspace_app.kb.index_run.IndexRunStore`; the difference is that
this run also carries the FE-facing ``status`` + ``proposals`` (the split job
returns before any proposal exists, so the run — not the split job — is what the
FE polls), and its id is generated by ``start`` (a run spans a doc *set*, so there
is no natural single key like the index run's doc id).
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from datetime import datetime

import msgspec
from specstar import QB, SpecStar
from specstar.types import PreconditionFailedError, ResourceIDNotFoundError, RevisionStatus

from .card_gen import CardGenRun, ProposedCard

_LOGGER = logging.getLogger(__name__)

# Per-run contention is bounded by the doc count; this is a generous backstop
# against a live-lock, not a tuning knob.
_MAX_CAS_RETRIES = 1000


class CardGenRunStore:
    """Read/CAS-write the per-run :class:`CardGenRun` join + FE-facing state."""

    def __init__(self, spec: SpecStar) -> None:
        self._rm = spec.get_resource_manager(CardGenRun)

    # ── seed / read ──────────────────────────────────────────────────
    def start(self, collection_id: str, doc_ids: list[str]) -> str:
        """Seed a fresh run over ``doc_ids`` (ordered, so finalize merges the
        staged digests deterministically) and return its id — what ``enqueue``
        hands back and the FE polls. Written as a draft revision so the split /
        process / finalize jobs can ``modify`` it in place under CAS (modify
        requires a draft). The run starts ``pending`` (PENDING to the FE) until
        the split job picks it up."""
        run = CardGenRun(collection_id=collection_id, doc_ids=list(doc_ids), total=len(doc_ids))
        return self._rm.create(run, status=RevisionStatus.draft).resource_id

    def get(self, run_id: str) -> CardGenRun | None:
        try:
            data = self._rm.get(run_id).data
        except ResourceIDNotFoundError:
            return None
        assert isinstance(data, CardGenRun)  # narrow Struct | Unset for ty
        return data

    # ── CAS mutations ────────────────────────────────────────────────
    def begin(self, run_id: str) -> None:
        """Flip ``pending`` → ``running`` when the split job picks the run up
        (PROCESSING to the FE while its process jobs run). Idempotent — a
        redelivered split leaves an already-running run untouched."""
        self._cas(run_id, lambda run: _to_running(run))

    def mark_done(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` was digested OK. Re-running
        the same process job (at-least-once redelivery) is a no-op."""
        self._cas(run_id, lambda run: _with_index(run, "done", doc_index))

    def mark_failed(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` gave up. Counts toward the
        finalize gate so a failed doc can't wedge the run in ``running`` forever."""
        self._cas(run_id, lambda run: _with_index(run, "failed", doc_index))

    def claim_finalize(self, run_id: str) -> bool:
        """Try to win the exactly-once finalize gate. Returns ``True`` for the
        single winner — only when every doc is accounted for
        (``done ∪ failed == total``) and the flag is not already claimed. All
        other finishers get ``False``. Crash-safe: if the winner dies before
        finalizing, the flag stays set but the finalize work is re-driven by
        redelivery; if it dies before even claiming, the gate is still open."""
        claimed = False

        def mutate(run: CardGenRun) -> CardGenRun | None:
            nonlocal claimed
            if run.finalized:
                return None  # already claimed by someone else
            if len(set(run.done) | set(run.failed)) < run.total:
                return None  # not every doc is accounted for yet
            claimed = True
            return msgspec.structs.replace(run, finalized=True)

        self._cas(run_id, mutate)
        return claimed

    def set_proposals(self, run_id: str, proposals: list[ProposedCard]) -> None:
        """Replace the run's reviewable proposals wholesale — finalize writes the
        merged/classified set; the review surface re-saves the reviewer's edited
        set. Written under CAS so it never clobbers a concurrent join write."""
        self._cas(run_id, lambda run: msgspec.structs.replace(run, proposals=list(proposals)))

    def finish(self, run_id: str, *, status: str) -> None:
        """Stamp the terminal status (``done`` / ``error``) once finalize has run
        — this is what flips the FE from PROCESSING to COMPLETED / FAILED."""
        self._cas(run_id, lambda run: msgspec.structs.replace(run, status=status))

    # ── review resolution (#415: leave the 待審核 queue) ──────────────
    def mark_committed(self, run_id: str) -> None:
        """Resolve a reviewed run as ``committed`` — its accepted proposals were
        written to cards, so it drops out of the review queue. Idempotent: only a
        finalized (``done``) run resolves; re-committing is a no-op."""
        self._cas(run_id, lambda run: _resolve(run, "committed"))

    def mark_dismissed(self, run_id: str) -> None:
        """Resolve a run as ``dismissed`` — the reviewer discarded its proposals;
        it leaves the queue without writing cards. Idempotent (only from ``done``)."""
        self._cas(run_id, lambda run: _resolve(run, "dismissed"))

    def pending_for_collection(self, collection_id: str) -> list[tuple[str, CardGenRun]]:
        """The collection's runs finalized and awaiting review — the 待審核 queue
        (#415), newest first. Queries the indexed ``done`` status (bounded: only
        unreviewed runs), then filters to the collection."""
        rows: list[tuple[str, datetime, CardGenRun]] = []
        for r in self._rm.list_resources((QB["status"] == "done").build()):
            d = r.data
            assert isinstance(d, CardGenRun)  # rm is CardGenRun-typed; narrows for ty
            if d.collection_id != collection_id:
                continue
            rows.append((r.info.resource_id, r.info.created_time, d))  # ty: ignore[unresolved-attribute]
        rows.sort(key=lambda t: t[1], reverse=True)  # newest first
        return [(rid, d) for rid, _ct, d in rows]

    # ── machinery ────────────────────────────────────────────────────
    def _cas(
        self, run_id: str, mutate: Callable[[CardGenRun], CardGenRun | None]
    ) -> CardGenRun | None:
        """Optimistic read-modify-write. ``mutate(run)`` returns the next run, or
        ``None`` to abort with no write (an idempotent no-op). Retries on a
        concurrent writer until it wins or the run vanishes."""
        for _ in range(_MAX_CAS_RETRIES):
            try:
                res = self._rm.get(run_id)
            except ResourceIDNotFoundError:
                return None  # run cascaded away (collection deleted mid-flight)
            run = res.data
            assert isinstance(run, CardGenRun)
            new = mutate(run)
            if new is None:
                return None
            try:
                self._rm.modify(
                    run_id,
                    new,
                    status=RevisionStatus.draft,
                    expected_etag=res.info.etag,  # ty: ignore[unknown-argument]
                )
                return new
            except PreconditionFailedError:
                continue  # another writer won the race — re-read and retry
        raise RuntimeError(f"CardGenRun CAS exhausted retries for {run_id}")  # pragma: no cover


def _to_running(run: CardGenRun) -> CardGenRun | None:
    """Flip a pending run to running; a no-op (skip the CAS write) once it has
    already begun, so a redelivered split job can't reset progress."""
    if run.status != "pending":
        return None
    return msgspec.structs.replace(run, status="running")


def _resolve(run: CardGenRun, status: str) -> CardGenRun | None:
    """Resolve a finalized run to a terminal review state (``committed`` /
    ``dismissed``). Only a ``done`` run resolves, so a double-commit / dismiss is
    an idempotent no-op (and a still-running run is never yanked out)."""
    if run.status != "done":
        return None
    return msgspec.structs.replace(run, status=status)


def _with_index(run: CardGenRun, field_name: str, doc_index: int) -> CardGenRun | None:
    """Append ``doc_index`` to ``run.{field_name}`` unless already present
    (idempotent). Returns ``None`` to signal "no change" so the CAS write is
    skipped entirely."""
    current: list[int] = getattr(run, field_name)
    if doc_index in current:
        return None
    return msgspec.structs.replace(run, **{field_name: [*current, doc_index]})
