"""CardGenRunStore — CAS join state for the card-gen fan-out (#414).

A card-generation run over N documents is fanned out into N small
``CardGenJob(kind="process")`` jobs (one per doc) so they parallelise across
worker pods. Those jobs run independently — possibly on different pods, possibly
in parallel — so "every doc is digested" is a fact no single job owns. This store
is the agreement point, and it is deliberately **queue-agnostic**: correctness
rests on compare-and-swap against the resource's etag, NOT on the queue's
``partition_key`` serialization (which the RabbitMQ backend silently ignores).

The finalize trigger is NOT "whoever recorded the last doc" — that races (two
finishers can both see the set fill) and loses on crash (the last recorder can
die before triggering). Instead every finisher re-evaluates the gate
``done ∪ failed == total`` and races to flip the ``finalized`` flag under CAS;
exactly one wins and triggers finalize, and a crash before finalize just leaves
the gate open for the next finisher to win.

Mirrors :class:`workspace_app.kb.index_run.IndexRunStore`; the difference is that
this run also carries the FE-facing ``status`` + ``proposals`` (the split job
returns before any proposal exists, so the run — not the split job — is what the
FE polls), and its id is generated by ``start`` (a run spans a doc *set*, so there
is no natural single key like the index run's doc id).
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from datetime import datetime

import msgspec
from specstar import QB, SpecStar
from specstar.types import PreconditionFailedError, ResourceIDNotFoundError, RevisionStatus

from .card_gen import CardGenRun, ProposedCard, ensure_proposal_ids, is_active

_LOGGER = logging.getLogger(__name__)

# Per-run contention is bounded by the doc count; this is a generous backstop
# against a live-lock, not a tuning knob.
_MAX_CAS_RETRIES = 1000


class CardGenRunStore:
    """Read/CAS-write the per-run :class:`CardGenRun` join + FE-facing state."""

    def __init__(self, spec: SpecStar) -> None:
        self._rm = spec.get_resource_manager(CardGenRun)

    # ── seed / read ──────────────────────────────────────────────────
    def start(self, collection_id: str, doc_ids: list[str]) -> str:
        """Seed a fresh run over ``doc_ids`` (ordered, so finalize merges the
        staged digests deterministically) and return its id — what ``enqueue``
        hands back and the FE polls. Written as a draft revision so the split /
        process / finalize jobs can ``modify`` it in place under CAS (modify
        requires a draft). The run starts ``pending`` (PENDING to the FE) until
        the split job picks it up."""
        run = CardGenRun(collection_id=collection_id, doc_ids=list(doc_ids), total=len(doc_ids))
        return self._rm.create(run, status=RevisionStatus.draft).resource_id

    def get(self, run_id: str) -> CardGenRun | None:
        try:
            data = self._rm.get(run_id).data
        except ResourceIDNotFoundError:
            return None
        assert isinstance(data, CardGenRun)  # narrow Struct | Unset for ty
        return data

    # ── CAS mutations ────────────────────────────────────────────────
    def begin(self, run_id: str) -> None:
        """Flip ``pending`` → ``running`` when the split job picks the run up
        (PROCESSING to the FE while its process jobs run). Idempotent — a
        redelivered split leaves an already-running run untouched."""
        self._cas(run_id, lambda run: _to_running(run))

    def mark_done(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` was digested OK. Re-running
        the same process job (at-least-once redelivery) is a no-op."""
        self._cas(run_id, lambda run: _with_index(run, "done", doc_index))

    def mark_failed(self, run_id: str, doc_index: int) -> None:
        """Idempotently record that doc ``doc_index`` gave up. Counts toward the
        finalize gate so a failed doc can't wedge the run in ``running`` forever."""
        self._cas(run_id, lambda run: _with_index(run, "failed", doc_index))

    def claim_finalize(self, run_id: str) -> bool:
        """Try to win the exactly-once finalize gate. Returns ``True`` for the
        single winner — only when every doc is accounted for
        (``done ∪ failed == total``) and the flag is not already claimed. All
        other finishers get ``False``. Crash-safe: if the winner dies before
        finalizing, the flag stays set but the finalize work is re-driven by
        redelivery; if it dies before even claiming, the gate is still open."""
        claimed = False

        def mutate(run: CardGenRun) -> CardGenRun | None:
            nonlocal claimed
            if run.finalized:
                return None  # already claimed by someone else
            if len(set(run.done) | set(run.failed)) < run.total:
                return None  # not every doc is accounted for yet
            claimed = True
            return msgspec.structs.replace(run, finalized=True)

        self._cas(run_id, mutate)
        return claimed

    def set_proposals(self, run_id: str, proposals: list[ProposedCard]) -> None:
        """Replace the run's reviewable proposals wholesale — finalize writes the
        merged/classified set; the review surface re-saves the reviewer's edited
        set. Assigns each proposal a stable id (#481) so the review table can
        address one card. Written under CAS so it never clobbers a concurrent join
        write."""
        stamped = ensure_proposal_ids(list(proposals))
        self._cas(run_id, lambda run: msgspec.structs.replace(run, proposals=stamped))

    def finish(self, run_id: str, *, status: str) -> None:
        """Stamp the terminal status (``done`` / ``error``) once finalize has run
        — this is what flips the FE from PROCESSING to COMPLETED / FAILED."""
        self._cas(run_id, lambda run: msgspec.structs.replace(run, status=status))

    # ── review resolution (#415: leave the 待審核 queue) ──────────────
    def mark_dismissed(self, run_id: str) -> None:
        """Resolve a run as ``dismissed`` — the reviewer discarded its proposals;
        it leaves the queue without writing cards. Idempotent (only from ``done``)."""
        self._cas(run_id, lambda run: _resolve(run, "dismissed"))

    # ── per-card review (#481: the review table addresses one card) ──
    def decide(self, run_id: str, card_id: str, decision: str) -> CardGenRun | None:
        """Set one proposal's decision by id (inline accept/reject), then settle the
        run out of the queue if that made every proposal terminal (#481). A no-op
        (returns ``None``) if the card id isn't found."""
        return self._cas(
            run_id,
            lambda run: _apply_and_settle(
                run, lambda ps: _replace_by_id(ps, card_id, lambda p: _redecide(p, decision))
            ),
        )

    def update_proposal(
        self, run_id: str, card_id: str, new_card: ProposedCard
    ) -> CardGenRun | None:
        """Replace one proposal by id with the reviewer's edited card (drawer edit:
        body/title + decision), keeping the id authoritative, then settle (#481).
        A no-op if the id isn't found."""
        return self._cas(
            run_id,
            lambda run: _apply_and_settle(
                run,
                lambda ps: _replace_by_id(
                    ps, card_id, lambda _p: msgspec.structs.replace(new_card, id=card_id)
                ),
            ),
        )

    def mark_proposals_committed(self, run_id: str, card_ids: list[str]) -> CardGenRun | None:
        """Advance the referenced ACTIVE proposals to ``committed`` (their cards were
        just written) and settle the run (#481). Only advances active cards, so a
        ref to an already-resolved card is skipped; returns ``None`` if nothing
        advanced (idempotent). The run resolves ``committed`` once no active card
        remains, or stays ``done`` if some are still pending — the partial-commit
        semantics: committed cards leave, the rest wait for another pass."""
        ids = set(card_ids)
        return self._cas(
            run_id,
            lambda run: (
                _apply_and_settle(
                    run,
                    lambda ps: _advance_committed(ps, ids),
                )
                if run.status == "done"
                else None
            ),
        )

    def runs_by_status(
        self, statuses: list[str], *, collection_id: str | None = None
    ) -> list[tuple[str, float, CardGenRun]]:
        """Every run in one of ``statuses``, as ``(run_id, created_epoch, run)``,
        newest first — the 審核 inbox's card-gen source (#481). One indexed
        ``status`` query (``in_``), so it never scans. ``collection_id`` (#506) adds
        the indexed ``collection_id`` predicate so the per-collection 待審核 tab
        reads only that collection's runs instead of every collection's."""
        query = QB["status"].in_(statuses)
        if collection_id is not None:
            query = (QB["collection_id"] == collection_id) & query
        rows: list[tuple[str, float, CardGenRun]] = []
        for r in self._rm.list_resources(query.build()):
            d = r.data
            assert isinstance(d, CardGenRun)  # rm is CardGenRun-typed; narrows for ty
            rows.append(
                (r.info.resource_id, r.info.created_time.timestamp(), d)  # ty: ignore[unresolved-attribute]
            )
        rows.sort(key=lambda t: t[1], reverse=True)  # newest first
        return rows

    def pending_for_collection(self, collection_id: str) -> list[tuple[str, CardGenRun]]:
        """The collection's runs finalized and awaiting review — the 待審核 queue
        (#415), newest first. Queries the indexed ``done`` status (bounded: only
        unreviewed runs), then filters to the collection."""
        rows: list[tuple[str, datetime, CardGenRun]] = []
        for r in self._rm.list_resources((QB["status"] == "done").build()):
            d = r.data
            assert isinstance(d, CardGenRun)  # rm is CardGenRun-typed; narrows for ty
            if d.collection_id != collection_id:
                continue
            rows.append((r.info.resource_id, r.info.created_time, d))  # ty: ignore[unresolved-attribute]
        rows.sort(key=lambda t: t[1], reverse=True)  # newest first
        return [(rid, d) for rid, _ct, d in rows]

    def sweep_empty_runs(
        self, *, collection_id: str | None = None, limit: int | None = None
    ) -> int:
        """Drain already-finalized EMPTY runs out of the 待審核 queue (#506): a run
        stuck in ``done`` with 0 proposals (finalized before the empty-status fix, or by
        a reconcile pass that suppressed every candidate) has nothing to review, so it is
        re-stamped ``empty`` — the terminal status excluded from BOTH inbox views. A
        ``done`` run that carries proposals is a real pending item and is skipped.
        Idempotent (converges to a no-op once the backlog is cleared); returns how many
        runs it drained. ``collection_id`` scopes the indexed query so the per-collection
        maintenance sweep touches only its own runs; ``limit`` bounds one pass."""
        query = QB["status"] == "done"
        if collection_id is not None:
            query = (QB["collection_id"] == collection_id) & query
        drained = 0
        for r in self._rm.list_resources(query.build()):
            # `_drain_empty` is the single decision point: it drains a done+empty run and
            # no-ops (returns None → no CAS write) for a run that still carries proposals
            # or has changed under us — so the count reflects only real drains.
            if self._cas(r.info.resource_id, _drain_empty) is not None:  # ty: ignore[unresolved-attribute]
                drained += 1
                if limit is not None and drained >= limit:
                    break
        return drained

    # ── machinery ────────────────────────────────────────────────────
    def _cas(
        self, run_id: str, mutate: Callable[[CardGenRun], CardGenRun | None]
    ) -> CardGenRun | None:
        """Optimistic read-modify-write. ``mutate(run)`` returns the next run, or
        ``None`` to abort with no write (an idempotent no-op). Retries on a
        concurrent writer until it wins or the run vanishes."""
        for _ in range(_MAX_CAS_RETRIES):
            try:
                res = self._rm.get(run_id)
            except ResourceIDNotFoundError:
                return None  # run cascaded away (collection deleted mid-flight)
            run = res.data
            assert isinstance(run, CardGenRun)
            new = mutate(run)
            if new is None:
                return None
            try:
                self._rm.modify(
                    run_id,
                    new,
                    status=RevisionStatus.draft,
                    expected_etag=res.info.etag,  # ty: ignore[unknown-argument]
                )
                return new
            except PreconditionFailedError:
                continue  # another writer won the race — re-read and retry
        raise RuntimeError(f"CardGenRun CAS exhausted retries for {run_id}")  # pragma: no cover


def _to_running(run: CardGenRun) -> CardGenRun | None:
    """Flip a pending run to running; a no-op (skip the CAS write) once it has
    already begun, so a redelivered split job can't reset progress."""
    if run.status != "pending":
        return None
    return msgspec.structs.replace(run, status="running")


def _resolve(run: CardGenRun, status: str) -> CardGenRun | None:
    """Resolve a finalized run to a terminal review state (``committed`` /
    ``dismissed``). Only a ``done`` run resolves, so a double-commit / dismiss is
    an idempotent no-op (and a still-running run is never yanked out)."""
    if run.status != "done":
        return None
    return msgspec.structs.replace(run, status=status)


def _drain_empty(run: CardGenRun) -> CardGenRun | None:
    """Sweep helper (#506): a finalized run with 0 proposals leaves the 待審核 queue as
    ``empty``. Returns ``None`` (no CAS write) for anything else — a still-open run or one
    that gained proposals since the read — so the drain is idempotent + race-safe."""
    if run.status != "done" or run.proposals:
        return None
    return msgspec.structs.replace(run, status="empty")


def _redecide(p: ProposedCard, decision: str) -> ProposedCard:
    return msgspec.structs.replace(p, decision=decision)


def _replace_by_id(
    proposals: list[ProposedCard], card_id: str, fn: Callable[[ProposedCard], ProposedCard]
) -> list[ProposedCard] | None:
    """Rebuild ``proposals`` with the one whose id is ``card_id`` passed through
    ``fn``. Returns ``None`` (a no-op) if no proposal has that id."""
    idx = next((i for i, p in enumerate(proposals) if p.id == card_id), None)
    if idx is None:
        return None
    out = list(proposals)
    out[idx] = fn(out[idx])
    return out


def _advance_committed(proposals: list[ProposedCard], ids: set[str]) -> list[ProposedCard] | None:
    """Flip each referenced ACTIVE proposal to ``committed``; returns ``None`` if
    none changed (idempotent — a ref to an already-resolved card advances nothing)."""
    out = [
        msgspec.structs.replace(p, decision="committed") if (p.id in ids and is_active(p)) else p
        for p in proposals
    ]
    return out if out != proposals else None


def _settle(run: CardGenRun) -> CardGenRun:
    """Resolve a finalized run out of the 待審核 queue once every proposal is
    terminal (#481): ``committed`` if any card was written, else ``dismissed``. A
    still-active or empty run is left ``done``. Only acts on a ``done`` run."""
    if run.status != "done" or not run.proposals or any(is_active(p) for p in run.proposals):
        return run
    resolved = "committed" if any(p.decision == "committed" for p in run.proposals) else "dismissed"
    return msgspec.structs.replace(run, status=resolved)


def _apply_and_settle(
    run: CardGenRun,
    transform: Callable[[list[ProposedCard]], list[ProposedCard] | None],
) -> CardGenRun | None:
    """Rebuild the run's proposals through ``transform`` (which sees the id-filled
    list — legacy blank ids are backfilled here and persisted on write, #481) and
    settle the run if that made every proposal terminal. ``transform`` returns the
    new list, or ``None`` to abort the CAS with no write."""
    filled = ensure_proposal_ids([msgspec.structs.replace(p) for p in run.proposals])
    new_proposals = transform(filled)
    if new_proposals is None:
        return None
    return _settle(msgspec.structs.replace(run, proposals=new_proposals))


def _with_index(run: CardGenRun, field_name: str, doc_index: int) -> CardGenRun | None:
    """Append ``doc_index`` to ``run.{field_name}`` unless already present
    (idempotent). Returns ``None`` to signal "no change" so the CAS write is
    skipped entirely."""
    current: list[int] = getattr(run, field_name)
    if doc_index in current:
        return None
    return msgspec.structs.replace(run, **{field_name: [*current, doc_index]})
