"""#441: parse the Keep a Changelog markdown into structured releases.

The CHANGELOG (``help_content/CHANGELOG.md``) is generated by git-cliff and is
the single source of truth for release notes on GitHub + the web. The web
``/help/releases`` view needs it as structured data (version → date → grouped
items) rather than one markdown blob, so this pure function turns the markdown
into a list of :class:`Release`. No I/O — the caller reads the file.
"""

from __future__ import annotations

import re

from pydantic import BaseModel

# "## [2026.07.06] — 2026-07-06" or "## [Unreleased]" (em dash + date optional).
_VERSION_RE = re.compile(r"^##\s+\[(?P<version>[^\]]+)\]\s*(?:—\s*(?P<date>.+))?$")
# "### Added"
_GROUP_RE = re.compile(r"^###\s+(?P<group>.+?)\s*$")
# "- did a thing"
_ITEM_RE = re.compile(r"^-\s+(?P<item>.+?)\s*$")


class ReleaseSection(BaseModel):
    """One ``### <group>`` block under a release — a Keep a Changelog category
    (Added / Fixed / Performance / Changed / Documentation) + its bullet items."""

    group: str
    items: list[str]


class Release(BaseModel):
    """One ``## [<version>] — <date>`` section of the changelog."""

    version: str
    date: str | None
    sections: list[ReleaseSection]
    unreleased: bool


def parse_changelog(text: str) -> list[Release]:
    releases: list[Release] = []
    for line in text.splitlines():
        vm = _VERSION_RE.match(line)
        if vm:
            version = vm.group("version").strip()
            date = vm.group("date")
            releases.append(
                Release(
                    version=version,
                    date=date.strip() if date else None,
                    sections=[],
                    unreleased=version.lower() == "unreleased",
                )
            )
            continue
        gm = _GROUP_RE.match(line)
        if gm and releases:
            releases[-1].sections.append(ReleaseSection(group=gm.group("group"), items=[]))
            continue
        im = _ITEM_RE.match(line)
        if im and releases and releases[-1].sections:
            releases[-1].sections[-1].items.append(im.group("item"))
            continue
    return releases
