"""#230: the platform "Platform Help" collection.

Usage docs + release notes live as packaged markdown under ``help_content/`` and
are seeded into a single, well-known KB collection at every boot — the repo is
the source of truth, so identical bytes are a no-op and edits ship with the
code. The collection is public to read/search (so the /help page's KB chat can
answer over it) but locked to its owner (the seeding system user) + superusers
for edits — i.e. admin-only edit, expressed purely with the #262 permission
model (no new access-control code).

#281 will later feed source-code-derived wiki into this SAME collection; nothing
here assumes the content stays markdown-from-repo.
"""

from __future__ import annotations

import logging
from pathlib import Path

from specstar import QB, SpecStar

from ..perm.model import ALL, Permission
from ..resources.kb import Collection
from .ingest import Ingestor

# The well-known name the collection is looked up / created by (its id is
# generated by specstar, so name is the stable handle across boots).
HELP_COLLECTION_NAME = "Platform Help"

# The seed owner: a dedicated, non-login system identity. Making it distinct
# from any real user is what makes the edit-lockdown hold even pre-SSO — in the
# single-tenant default every request is `default_user`, so if `default_user`
# owned the collection it could edit it. Owned by `system` instead, only
# superusers (+ the phantom system account nobody logs in as) can write.
HELP_SYSTEM_USER = "system"


def help_content_dir() -> Path:
    """The packaged directory holding the curated end-user help markdown.

    Lives inside the package (not the repo root) so it ships with the wheel and
    is always present at runtime regardless of CWD."""
    return Path(__file__).resolve().parent.parent / "help_content"


def _help_permission() -> Permission:
    """Public to read + search + chat; every write verb (add/edit content,
    write_meta, execute, delete) falls to the owner + superusers only.

    NOTE: ``visibility="public"`` would grant ALL verbs to everyone (the
    back-compat "fully open" meaning — see ``perm.authorize``), and
    ``permission=None`` is the same. To lock writes while keeping reads open we
    use ``restricted`` and grant only the read-side verbs to the ``ALL``
    wildcard (``read_meta`` so it's still listed/visible to everyone)."""
    return Permission(
        visibility="restricted",
        read_meta=[ALL],
        read_content=[ALL],
        read_chat=[ALL],
        converse=[ALL],
    )


def ensure_help_collection(
    spec: SpecStar, *, name: str = HELP_COLLECTION_NAME, owner: str = HELP_SYSTEM_USER
) -> str:
    """Idempotently ensure the help collection exists with the locking
    permission, owned by ``owner``, returning its id.

    Cheap (no embedding / ingestion) so it always succeeds even when the
    embedder is down — the /help page can still render its docs while AI search
    waits for the embedder."""
    rm = spec.get_resource_manager(Collection)
    for r in rm.list_resources(QB.all()):  # ty: ignore[invalid-argument-type]
        if isinstance(r.data, Collection) and r.data.name == name:
            return r.info.resource_id  # ty: ignore[unresolved-attribute]
    with rm.using(user=owner):
        return rm.create(Collection(name=name, permission=_help_permission())).resource_id


def _ingest_help_docs(
    ingestor: Ingestor, cid: str, *, user: str, content_dir: Path | None = None
) -> None:
    """Upsert every ``*.md`` in ``content_dir`` (the packaged dir by default)
    as a SourceDoc owned by ``user``. The Ingestor de-dups identical bytes, so
    re-ingesting unchanged content is a no-op."""
    src = content_dir if content_dir is not None else help_content_dir()
    for md in sorted(src.glob("*.md")):
        ingestor.ingest(
            collection_id=cid,
            user=user,
            filename=md.name,
            data=md.read_bytes(),
        )


def seed_help_collection(
    spec: SpecStar,
    ingestor: Ingestor,
    *,
    user: str = HELP_SYSTEM_USER,
    name: str = HELP_COLLECTION_NAME,
    content_dir: Path | None = None,
) -> str:
    """Ensure the collection (owned by ``user``), then upsert its docs. Raises
    on ingestion failure — callers at boot use ``seed_help_collection_best_effort``
    instead so an embedder hiccup never blocks startup. Returns the id."""
    cid = ensure_help_collection(spec, name=name, owner=user)
    _ingest_help_docs(ingestor, cid, user=user, content_dir=content_dir)
    return cid


def seed_help_collection_best_effort(
    spec: SpecStar,
    ingestor: Ingestor,
    *,
    user: str = HELP_SYSTEM_USER,
    logger: logging.Logger | None = None,
) -> str:
    """Boot-time seed: ensure the collection (cheap, reliable) ALWAYS, then
    ingest its docs best-effort. A failure (e.g. the embedder is down) is logged
    and swallowed so the collection stays readable-but-unindexed instead of
    blocking boot. Returns the collection id (always)."""
    cid = ensure_help_collection(spec, owner=user)
    try:
        _ingest_help_docs(ingestor, cid, user=user)
    except Exception:  # noqa: BLE001 — best-effort; never block boot on a seed
        (logger or logging.getLogger(__name__)).exception("help content seed failed")
    return cid
