view: chart
source: data/a.csv
highlight:
  values: {item: [r1, r2]}
layer:
  - mark: {type: bar, stack: true}
    encoding:
      x: {field: value, type: quantitative}
      y: {field: group, type: nominal}
  - mark: scatter
    encoding:
      x: {field: value, type: quantitative}
      y: {field: group, type: nominal}
