from __future__ import annotations

from typing import Protocol


class FileNotFound(LookupError):
    """Raised when a path does not exist in a workspace's file store."""


class FileStore(Protocol):
    async def write(self, workspace_id: str, path: str, data: bytes) -> None: ...
    async def read(self, workspace_id: str, path: str) -> bytes: ...
    async def ls(self, workspace_id: str, prefix: str = "") -> list[str]: ...
    async def exists(self, workspace_id: str, path: str) -> bool: ...
    async def delete(self, workspace_id: str, path: str) -> None: ...

    # Dirty-path tracking — drives SandboxSync.flush before each exec, so
    # the sandbox sees the latest FileStore writes the agent just made.
    def dirty_paths(self, workspace_id: str) -> set[str]: ...
    def clear_dirty(self, workspace_id: str) -> None: ...
