// Auto-generated by AutoCRUD Web Generator
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { ResourceDetail } from '../../../autocrud/lib/components/ResourceDetail';
import { getResource } from '../../../autocrud/lib/resources';

type DetailSearch = { revision?: string };

export const Route = createFileRoute('/autocrud-admin/citation-event/$resourceId')({
  component: DetailPage,
  validateSearch: (search: Record<string, unknown>): DetailSearch => ({
    revision: typeof search.revision === 'string' ? search.revision : undefined,
  }),
});

function DetailPage() {
  const { resourceId } = Route.useParams();
  const { revision } = Route.useSearch();
  const navigate = useNavigate({ from: '/autocrud-admin/citation-event/$resourceId' });

  const config = getResource('citation-event')!;

  const handleRevisionChange = (rev: string | null) => {
    navigate({
      search: { revision: rev ?? undefined },
      replace: true,
    });
  };

  return (
    <ResourceDetail
      config={config}
      resourceId={resourceId}
      basePath="/autocrud-admin/citation-event"
      initialRevision={revision}
      onRevisionChange={handleRevisionChange}
    />
  );
}
