// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { ResourceCreate } from '../../../autocrud/lib/components/ResourceCreate';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/wiki-build-state/create')({
  component: CreatePage,
});

function CreatePage() {
  const config = getResource('wiki-build-state')!;
  return <ResourceCreate config={config} basePath="/autocrud-admin/wiki-build-state" />;
}
