// Auto-generated by AutoCRUD Web Generator
import { createFileRoute } from '@tanstack/react-router';
import { Container } from '@mantine/core';
import { ResourceTable } from '../../../autocrud/lib/components/ResourceTable';
import { getResource } from '../../../autocrud/lib/resources';

export const Route = createFileRoute('/autocrud-admin/wiki-build-state/')({
  component: ListPage,
});

function ListPage() {
  const config = getResource('wiki-build-state')!;
  return (
    <Container size="xl" py="xl">
      <ResourceTable config={config} basePath="/autocrud-admin/wiki-build-state" />
    </Container>
  );
}
